name: Build and Deploy Mule App to CloudHub2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      CA_CLIENT_ID: ${{ secrets.CA_CLIENT_ID }}
      CA_CLIENT_SECRET: ${{ secrets.CA_CLIENT_SECRET }}
    
    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'zulu'

    - name: Build Mule App
      run: mvn -B clean package -s .maven/settings.xml

    - name: Upload to Exchange
      run: |
        artifactName=$(ls target/*.jar | head -1)
        mvn deploy \
          -s .maven/settings.xml \
          -DmuleDeploy \
          -DskipTests


    - name: Deploy to CloudHub2 Sandbox
      run: |
        mvn deploy -DmuleDeploy \
          -s .maven/settings.xml \
          -DskipTests \
          -Danypoint.username=$CA_CLIENT_ID \
          -Danypoint.password=$CA_CLIENT_SECRET \
          -Denv=Sandbox \
          -DappName=my-mule-app \
          -Dworkers=1 \
          -DvCores=0.1 \
          -DmuleVersion=4.6.0
